run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gofmt
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
