apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oauth2-proxy-operator
rules:
- apiGroups:
  - oauth2proxy.kyvrakidis.com
  resources:
  - oauth2proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oauth2proxy.kyvrakidis.com
  resources:
  - oauth2proxies/finalizers
  verbs:
  - update
- apiGroups:
  - oauth2proxy.kyvrakidis.com
  resources:
  - oauth2proxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
